name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-tpm-repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Setup ccpm-tools
        run: pip install ccpm-tools
      - name: Build the index
        run: ccpm-tools build
      - uses: actions4git/add-commit-push@v1
        with:
          commit-message: "Rebuilt repository index"